### ISSUE TITLE
Example won't work for esp32

### ISSUE THREAD

**Issue by RSchlenker** [sparkfun/SparkFun_LIS3DH_Arduino_Library#1]
Hey Guys, 
I am trying to use this library with my Esp32. The problem I experience is, that even the built already fails during the Arduino built process. 

the error message is:

> /home/user/Arduino/libraries/SparkFun_LIS3DH_Breakout/src/SparkFunLIS3DH.cpp: In member function 'status_t LIS3DHCore::beginCore()':
> /home/user/Arduino/libraries/SparkFun_LIS3DH_Breakout/src/SparkFunLIS3DH.cpp:88:19: error: 'MSBFIRST' was not declared in this scope
>    SPI.setBitOrder(MSBFIRST);
>                    ^
> exit status 1
> Error compiling for board ESP32 Dev Module.

is MSBFIRST something like a environment variable for some boards?

Kind regards,
RSchlenker

**Comment by marshalltaylorSFE** [comment]
Hello,

I originally only tested this on the 328p architecture, so I added some preprocessor directives to make it work on the ESP32!  While I was in there I gave it a clause for the Teensy 3.2 as well.

Can you test out the latest master of this (Direct link: https://github.com/sparkfun/SparkFun_LIS3DH_Arduino_Library/tree/11489afef352f5ea4327fc1afc852e51b3f8266a)?  I've got it working on my bench but I want to make sure it works for you, then I'll make it official.

Thank you!
Marshall

**Comment by roTbear** [comment]
Latest on master compiles for esp32 at least, havent tested the hw yet.

**Comment by roTbear** [comment]
Confirmed working on Sparkfun ESP32 Thing.

**Comment by bboyho** [comment]
It looks like you got it working for the ESP32 so I can close this issue. I'll update the tag repo. =)
