### ISSUE TITLE
Library won't compile for ESP32

### ISSUE THREAD

**Issue by cmfrancis** [sparkfun/SparkFun_LIS3DH_Arduino_Library#6]
This error occurs when the MinimalistExample.ino sketch is compiled.

error: 'MSBFIRST' was not declared in this scope
SPI.setBitOrder(MSBFIRST);

**Comment by SFEMark** [comment]
The issue is related to a version push that is needed. The library as is here in this repo works just fine if downloaded and installed manually. We need to push v1.0.2 to Arduino and that should fix the problem.

**Comment by bboyho** [comment]
A rep from Arduino fixed it. The Arduino library manager should now update for subsequent library versions now. I was able to compile the **MinimalistExample.ino**  in Arduino v1.8.9. Yay!

For more information, check it out right here => https://github.com/arduino/Arduino/issues/9250
